import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * OtherEurowalkWebsite
 * Id: 7ef3f5bb-f230-44c9-be69-31bd500aeb92
 * Codename: other_eurowalk_website
 */
export type OtherEurowalkWebsite = IContentItem<{
  /**
   * Text (text)
   * Required: true
   * Id: 9ec99f10-d68a-454f-aa43-e4a9b175d1bf
   * Codename: _title
   */
  title: Elements.TextElement;
  /**
   * Text (text)
   * Required: true
   * Id: 9ec99f10-d68a-454f-aa43-e4a9b175d1bf
   * Codename: _website_url
   */
  website_url: Elements.TextElement;
}>;
