import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type WalkSingleLocation } from './walk_single_location';

/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Walk
 * Id: 98d902da-b805-44a2-aab8-402fd735335d
 * Codename: walk
 */
export type Walk = IContentItem<{
  /**
   * Locations (modular_content)
   * Required: false
   * Id: 43377107-24ee-453b-a5f5-f1c4f5bbe548
   * Codename: locations_of_walk
   */
  locations_of_walk: Elements.LinkedItemsElement<WalkSingleLocation>;

  /**
   * Number (number)
   * Required: true
   * Id: 7c63cdf1-5154-499e-a486-db46d526afa9
   * Codename: number
   */
  number: Elements.NumberElement;

  /**
   * Overview picture (asset)
   * Required: true
   * Id: ffc37f27-f012-4db0-a579-ef16785aed91
   * Codename: overview_picture
   */
  overview_picture: Elements.AssetsElement;

  /**
   * Description (text)
   * Required: true
   * Id: 630404a0-47b3-4c38-ba99-65a99dd1cb77
   * Codename: short_description
   */
  short_description: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: e46bee87-8d2e-4f6b-85e9-e9eb8c40c61b
   * Codename: title
   */
  title: Elements.TextElement;
}>;
