import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Walk single location
 * Id: 7ef3f5bb-f230-44c9-be69-31bd500aeb92
 * Codename: walk_single_location
 */
export type WalkSingleLocation = IContentItem<{
  /**
   * Information about location (text)
   * Required: true
   * Id: 0bc0c32b-efb3-42eb-8efd-5a5b75e79da7
   * Codename: information_about_location
   */
  information_about_location: Elements.TextElement;

  /**
   * Latitude (number)
   * Required: true
   * Id: c42e6c9b-6008-4503-b43a-36e919943ea1
   * Codename: latitude
   */
  latitude: Elements.NumberElement;

  /**
   * Longitude (number)
   * Required: true
   * Id: 242b9229-59f8-44d1-abca-97bf24338eb1
   * Codename: longitude
   */
  longitude: Elements.NumberElement;

  /**
   * Order (number)
   * Required: false
   * Id: 7c032f4f-3e8b-4f8b-87ec-5c632b4751b1
   * Codename: order
   */
  order: Elements.NumberElement;

  /**
   * Picture (asset)
   * Required: false
   * Id: d12a39dc-3912-4e8c-94aa-bd4d8d792f2c
   * Codename: picture
   */
  picture: Elements.AssetsElement;

  /**
   * Title (text)
   * Required: true
   * Id: 9ec99f10-d68a-454f-aa43-e4a9b175d1bf
   * Codename: title
   */
  title: Elements.TextElement;
}>;
